server:
  port: 8888
spring:
  redis:
    host: localhost
    port: 6379
    #    password: root@666666
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: zjiah.mail@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: drteriabtpjhcadi
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: reggie_take_out
  #  datasource:
  #    hikari:
  #      connection-timeout: 7200000
  #    druid:
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  #      username: root
  #      password: 666666
  sharding-sphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.239.100:3306/reggie?characterEncoding=utf-8
        username: root
        password: 666666
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.239.129:3306/reggie?characterEncoding=utf-8
        username: root
        password: 666666
    masters-lave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin  #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

#阿里云OSS而配置文件
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tHGtxNZRiKzuMhsFbhd
    accessKeySecret: Iop1plZFRUTDSaKgjoM2rnpxAhEtBl
    bucketName: empfile



#自定义参数
reggie:
#  imgpath: A:\reggieimg\
  imgpath: /usr/local/reggie_image/
